# Generated by Django 5.2 on 2025-04-03 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome')),
                ('estudio', models.ManyToManyField(to='worstmovieapi.estudio')),
                ('produtor', models.ManyToManyField(to='worstmovieapi.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('concorrentes', models.ManyToManyField(to='worstmovieapi.filme')),
                ('ganhador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ganhador', to='worstmovieapi.filme')),
            ],
        ),
    ]
